---
- hosts: servers
  vars_files:
    - vars.yml
  gather_facts: true
  become: yes

  tasks:
    - name: Install system packages
      apt: pkg={{ item }}
      with_items:
        - git
        - nginx
        - gunicorn
        - postgresql
        - postgresql-server-dev-all
        - python-pip
        - python-dev
        - python-psycopg2

    - name: Save ssh key to server
      copy:
        src: "{{ ssh_private_key }}"
        dest: /root/.ssh/id_rsa mode=600

    - name: Create directory for app
      file:
        path: "{{ install_root }}/{{ project_name }}"
        state: directory

    - name: make sure postgresql server is running
      service:
        name: postgresql
        state: started

    - name: create database
      become_user: postgres
      postgresql_db:
        name: "{{ db_name }}"

    - name: create database user
      become_user: postgres
      postgresql_user:
        db: "{{ db_name }}"
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        priv: ALL

    - name: remove default nginx site
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

- include: deploy.yml