# Generated by Django 3.2.9 on 2021-11-17 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0002_students_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
